[project]
name = "da-code"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "duckdb>=1.4.4",
    "fuzzywuzzy>=0.18.0",
    "gymnasium>=1.2.3",
    "joblib>=1.5.3",
    "json5>=0.13.0",
    "jsonlines>=4.0.0",
    "matplotlib>=3.10.8",
    "nltk>=3.9.2",
    "numpy>=2.4.1",
    "openai>=2.15.0",
    "opencv-python>=4.13.0.90",
    "pandas>=3.0.0",
    "pillow>=12.1.0",
    "pyyaml>=6.0.3",
    "rouge>=1.0.1",
    "scikit-learn>=1.8.0",
]
